import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './routes/auth.routes.js';
import chatRoutes from './routes/chat.routes.js';
import db, { mainDb, vectorDb } from './config/db.js';

dotenv.config(); // Load .env file

// Generate a unique secret for this server instance.
// This ensures all users are logged out if the server/machine restarts.
const BOOT_SALT = Math.random().toString(36).substring(7);
process.env.JWT_SECRET = (process.env.JWT_SECRET || 'fallback_secret') + '_' + BOOT_SALT;

console.log('Environment Config Loaded');
console.log('DB Name:', process.env.DB_NAME);
console.log('N8N Webhook URL Present:', !!process.env.NEXT_PUBLIC_N8N_WEBHOOK_URL);
if (process.env.NEXT_PUBLIC_N8N_WEBHOOK_URL) {
  console.log('N8N Webhook URL:', process.env.NEXT_PUBLIC_N8N_WEBHOOK_URL.substring(0, 30) + '...');
}
console.log('Ollama Host:', process.env.OLLAMA_HOST);

const app = express();
// Default to 3005 for Production/K8s consistency if not specified in env
const PORT = process.env.PORT || 3005;

app.use(cors({
  origin: function (origin, callback) {
    const allowed = [
      'http://localhost:3000',
      'http://127.0.0.1:3000',
      'http://localhost:3005',     // Production/Docker port
      'http://127.0.0.1:3005',
      'http://10.0.1.159:3000',
      'http://10.0.1.159:30005',    // Production/Docker port
      'http://10.2.0.57:3000',     // Previous User's Network IP
      'http://10.2.0.63:3000',     // Current User's Network IP
      `http://localhost:${PORT}`,  // Dynamic port from env
      `http://127.0.0.1:${PORT}`,  // Dynamic port from env
      undefined // Allow non-browser tools like Postman/curl
    ];
    if (allowed.indexOf(origin) !== -1 || !origin) {
      callback(null, true);
    } else {
      console.warn(`Blocked CORS from: ${origin}`);
      callback(new Error('Not allowed by CORS'));
    }
  },
  credentials: true
}));
app.use(express.json());

// Request Logger (Debug)
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});

// Serve uploaded files
app.use('/uploads', express.static('server/uploads'));

// Routes
// Test Route (Placed before other routes to ensure priority)
// Serve static files from the React app (Frontend)
// The 'dist' folder is generated by 'npm run build' in the root directory
// Serve static files from the React app (Frontend) - PRODUCTION ONLY
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const distPath = path.join(__dirname, '../dist');

if (process.env.NODE_ENV === 'production') {
  app.use(express.static(distPath));
}

// API Routes will be handled below (lines 60-61), so this catch-all
// should be placed AFTER API routes if we want to valid 404s for API,
// BUT Express executes sequentially. 
// Standard pattern: 
// 1. Static Files
// 2. API Routes
// 3. Catch-all for SPA


// Enhanced Health Check (DB Connected?)
app.get('/health', async (req, res) => {
  try {
    await mainDb.query('SELECT 1');
    // Note: vectorDb query check might block if the pool is exhausted or strict connectivity is required
    // For now, we check mainDb as critical path.
    res.json({
      status: 'healthy',
      checks: { database: 'connected' },
      uptime: process.uptime(),
      timestamp: new Date().toISOString()
    });
  } catch (e) {
    console.error('Health Check Failed:', e);
    res.status(503).json({ status: 'unhealthy', error: e.message });
  }
});

app.get('/api/health', (req, res) => {
  res.status(200).json({ status: 'ok', uptime: process.uptime(), timestamp: new Date().toISOString() });
});

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/chat', chatRoutes);

// Catch-all (Production)
if (process.env.NODE_ENV === 'production') {
  app.get(/.*/, (req, res) => {
    res.sendFile(path.join(distPath, 'index.html'));
  });
}

// Database Initialization with Retry Logic
const initDB = async (retries = 5, delay = 5000) => {
  for (let i = 0; i < retries; i++) {
    try {
      console.log(`[DB] Attempting to connect... (Attempt ${i + 1}/${retries})`);
      await mainDb.query('SELECT 1');
      console.log('✅ Main DB Connected');

      await vectorDb.query('CREATE EXTENSION IF NOT EXISTS vector');
      console.log('✅ Vector DB Connected & Extension Verified');
      return true; // Success!
    } catch (e) {
      console.error(`❌ DB Connection Attempt ${i + 1} failed:`, e.message);
      if (i < retries - 1) {
        console.log(`[DB] Retrying in ${delay / 1000}s...`);
        await new Promise(res => setTimeout(res, delay));
      }
    }
  }
  console.error('🛑 Critical: Could not connect to Database after multiple attempts.');
  return false;
};

// Start Server & Handle Shutdown
const server = app.listen(PORT, async () => {
  await initDB();
  console.log(`🚀 Server running on port ${PORT}`);
});

server.on('error', (e) => {
  if (e.code === 'EADDRINUSE') {
    console.error(`❌ ERROR: Port ${PORT} is already in use.`);
  } else {
    console.error('❌ Server error:', e);
  }
});

// Graceful Shutdown
const attemptShutdown = async (signal) => {
  console.log(`\n🛑 ${signal} received. Starting graceful shutdown...`);

  server.close(async () => {
    console.log('HTTP server closed.');
    try {
      await mainDb.end();
      await vectorDb.end();
      console.log('Database connections closed.');
      process.exit(0);
    } catch (err) {
      console.error('Error during database disconnect:', err);
      process.exit(1);
    }
  });

  // Force exit if hanging
  setTimeout(() => {
    console.error('Force shutdown after timeout.');
    process.exit(1);
  }, 10000); // 10s
};

process.on('SIGTERM', () => attemptShutdown('SIGTERM'));
process.on('SIGINT', () => attemptShutdown('SIGINT'));
